#!/usr/local/bin/python

import sys
import urllib2
import json

SLUSH_STATS = 'https://mining.bitcoin.cz/accounts/profile/json/your_api_key_here'
WORKER_NAME = 'your_worker_name'

command = ''
if len(sys.argv) > 1:
    command = sys.argv[1]

if command == 'config':
    print "graph_title Slush Hashrate"
    print "graph_vlabel MHash/s"
    print "graph_category cryptocoin"
    print "Hashrate.label Hashrate"
    sys.exit(0)

mining_stats_raw = urllib2.urlopen(SLUSH_STATS)
mining_stats = json.load(mining_stats_raw)
hash_rate = mining_stats['workers'][WORKER_NAME]['hashrate']
print "Hashrate.value %d" % int(hash_rate)
