#!/usr/local/bin/python

import sys
import httplib
import re

zip_code = 94043

command = ''
if len(sys.argv) > 1:
    command = sys.argv[1]

if command == 'config':
    print "graph_title Mountain View Temperature"
    print "graph_vlabel Temp [F]"
    print "graph_category cryptocoin"
    print "Temperature.label Temperature"
    sys.exit(0)

conn = httplib.HTTPConnection('xhtml.weather.com')
conn.request('GET', '/xhtml/cc/' + str(zip_code))
response = conn.getresponse()
if not response.status == httplib.OK:
    print response.status
    sys.exit(1)

#>60\xc2\xb0F<
temp_match = re.search('>(\d+).*F<', response.read())
if temp_match:
    print "Temperature.value " + temp_match.group(1)
else:
    sys.exit(1)
